---

- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all

  tasks:
  - name: deploy ec2 key
    ec2_key:
      name: "{{ ec2_keypair }}"
      key_material: "{{ key_material }}"
      state: present

  - name: Launch ec2
    ec2:
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      count_tag: "{{ ec2_tag }}"
      exact_count: 2
      instance_tags: 
        name: "{{ ec2_tag }}"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: "{{ ec2.instances }}"

  - name: create elb
    ec2_elb_lb:
      name: "{{ elb_name }}"
      state: present
      zones:
        - ap-northeast-1a
        - ap-northeast-1c
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/index.html"
        response_timeout: 5
        interval: 10
        unhealthy_threshold: 2
        healthy_threshold: 4
  
  - name: register ec2 to elb
    ec2_elb:
      instance_id: "{{ item.id }}"
      ec2_elbs: "{{ elb_name }}"
      state: present
      validate_certs: no
      wait: no
    with_items: "{{ ec2.instances }}"

- hosts: ec2hosts
  name: set up ec2
  user: ec2-user
  become: yes
  become_user: root
  gather_facts: true

  tasks:
    - name: Check NTP service
      service: name=ntpd state=started

    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
