---

- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all

  tasks:
  # Creates a new ec2 key pair named `example` if not present using provided key
  # material.  This could use the 'file' lookup plugin to pull this off disk.
  - name: pip install requests
    pip:
      name: "requests"
  
  - name: launch server
    niftycloud:
      access_key: "{{ access_key }}"
      secret_access_key: "{{ secret_access_key }}"
      endpoint: "{{ endpoint }}"
      instance_id: "{{ item }}"
      state: "{{ state }}"
      image_id: "{{ image_id }}"
      key_name: "{{ key_name }}"
      security_group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      availability_zone: "{{ availability_zone }}"
      accounting_type: "{{ accounting_type }}"
      ip_type: "{{ ip_type }}"
    with_items:
      "{{ instance_ids }}"
      # startup_script: "roles/infrastructure/template/startup_script"
      # startup_script_vars:
      #   dummy_var: "DUMMY"
      # network_interface:
      #   - network_id: net-COMMON_GLOBAL
      #     ipAddress: "0.0.0.0"

  # - name: Regist server to load balancer
  #   niftycloud_lb:
  #     access_key: "{{ access_key }}"
  #     secret_access_key: "{{ secret_access_key }}"
  #     endpoint: "{{ endpoint }}"
  #     instance_id: "{{ item }}"
  #     instance_port: "{{ instance_port }}"
  #     loadbalancer_name: "{{ loadbalancer_name }}"
  #     loadbalancer_port: "{{ loadbalancer_port }}"
  #     state: "present"
  #   with_items: "{{ instance_ids }}"
